### ISSUE TITLE
TBA API v3

### ISSUE THREAD

**Issue by bdaroz** [JadenMcElvey/4112-Cpp-TBA-Scouting#1]
I saw your issue on the TBA repo. (the-blue-alliance/the-blue-alliance#2033)

I took a quick look at your library and wanted to mention something that came up recently on Chief Delphi. Depending on where you run your API from, and what Cloudflare (TBA's outermost caching service) thinks of your IP address, you may need to provide a valid HTTP `User-Agent` string. 

It wasn't clear from your code if one is being set by cURL by default, or if you may need to specify one.

I also took a quick look at `/src/TBAstatus.cpp` and noticed you are doing a full string comparison for error checking. That string isn't the only way TBA will indicate an error, and there's no guarantee that string won't change. Instead I'd try parsing it to a JSON object and check for an `error` property instead.

**Comment by JadenMcElvey** [comment]
Thank you for the feedback. Those are a couple things that I hadn't considered. I'll make sure to add a user agent property and improve the error detection in the next release version.
